name: Liquibase MySQL CI

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download MySQL Driver
        run: wget https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar -O mysql-connector-j.jar

      - name: Run Liquibase Migration
        uses: liquibase/liquibase-github-action@v4
        with:
          operation: 'update'
          classpath: 'mysql-connector-j.jar'
          changeLogFile: 'liquibase/changelog/changelog-master.xml'
          url: 'jdbc:mysql://mysql:3306/mydatabase'
          username: 'root'
          password: ${{ secrets.DB_PASSWORD }}
          driver: 'com.mysql.cj.jdbc.Driver'

  create-tag:
    needs: migrate-database
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para leer el historial de tags anteriores

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}